SkillTest/config/routes.rb
Rails.application.routes.draw do

  #ユーザー登録
  namespace :admin do
    root :to => 'home#index'
    resource :user,:except => [:index]
    resources :home, :only => [:index]
    resources :user_sessions, :only => [:new, :create, :destroy]
    resources :sites, :products
  end
  
  #ログイン
  get    'login',   to: 'admin/user_sessions#new'
  post   'login',   to: 'admin/user_sessions#create'
  get '/admin/logout' => 'admin/user_sessions#destroy', :as => 'admin_logout'
  
  
  concern :taggables do
    resources :tags, only: [:index]
  end
  
  #フロント
  resources :sites, path: '', only: [:index, :show] do
    resources :products, concerns: :taggables, only: [:show]
    resources :tags, only: [:show]
  end
  
  #エラーハンドリング
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

SkillTest/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :site
  
  #バリデーション
  validates :amazon_id, :price, :image, :title, :description, presence: true
  
  after_initialize :set_defaults, unless: :persisted?
  
  #画像アップロード用
  mount_uploader :image, ImageUploader
  
  #タグ用
  acts_as_taggable_on :tags
  
  #Pager用 - ページごとの数
  self.per_page = 20

  def set_defaults
    self.active = true if self.active.nil?
  end
end

SkillTest/app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :get_product, only: [:show, :edit,:update,:destroy]
  
  def index
    @site = Site.find(params[:site_id])
    @products = Product.where(site_id: @site.id)
                      .paginate(:page => params[:page])
                      .order_id_desc
  end
  
  def show
    @site = Site.friendly.find(@product.site_id)
    check_valid_user(@site)
      return  if performed?
  end
  
  def new
    @product = Product.new
  end
  
  def edit
    @site = Site.friendly.find(@product.site_id)
    check_valid_user(@site)
      return  if performed?
  end
  
  def create
     @site = Site.find(params[:product][:site_id])
     @product = Product.new(product_params)
     @product.site = @site
    
    if @product.save
    redirect_to admin_product_path(@product)
    else
      render 'new'
    end
  end

  def update
   @site = Site.friendly.find(@product.site_id)
   check_valid_user(@site)
    return  if performed?
   
  if @product.update(product_params)
    redirect_to admin_product_path(@product)
  else
    render 'edit'
    end  
  end

  def destroy
      @site = Site.friendly.find(@product.site_id)
      check_valid_user(@site)
        return  if performed?
    
      if @product.destroy
        redirect_to admin_products_path(:site_id => params[:site_id]),notice: '削除成功しました。'
      else
        redirect_to admin_products_path(:site_id => params[:site_id]),alert: '削除失敗しました。'
      end
  end
  
  private
   def product_params
     params.require(:product).permit(:amazon_id, :price, :title, :description, :image, :tag_list)
   end
   
  def get_product
    @product = Product.find(params[:id])
  end
end

SkillTest/app/controllers/products_controller.rb
class ProductsController < FrontBaseController
  before_action :get_site 
  
  def show
    @product = Product
               .includes(:site)
               .where(id: params[:id])
               .active
               .first
               
    
    if @product.blank?
      raise ActionController::RoutingError.new('商品が見つかりません。')
    end
    
    @related_products = Product
                        .tagged_with(@product.tag_list)
                        .where
                        .not(id: @product.id)
                        .limit(5)
  end
end

SkillTest/app/helpers/product_helper.rb
module ProductHelper
end

SkillTest/app/views/products/show.html.erb
<div id = "main" class= "col-lg-12">
    <div class="main_product_area">
      <div class="detail_left">
        <p>
        <%= image_tag @product.image.url %>
        </p>  
      </div>

      <div class="detail_right">
        <h1><%= @product.title %></h1>
        <p>
         <strong>Amazonリンク:</strong>
         <br>
         <a href="https://www.amazon.co.jp/dp/<%= @product.amazon_id %>/">詳細へ</a>
       </p>

       <p>
         <strong>価格:</strong>
         <br>
         <%= @product.price %>円
       </p>

       <p>
         <strong>説明:</strong>
         <br>
         <span id="description_span"><%= @product.description %></span>
       </p>
       <p>
         <strong>タグ:</strong>
         <br>
         <%= link_to 'この商品のタグ一覧へ', site_product_tags_path(product_id: @product.id) %>
       </p>
      </div>

      
      <h1 class="text-right site-heading">Related products</h1>
      <div class="related_product_area">
        <% @related_products.each do |product| %>

          <div class="grid-item">    
              <%=link_to(site_product_path(params[:site_id],product)) do%>   
                <div><%= image_tag product.image %></div>
                <div class="product_area_title"><%= product.title %></div>
              <% end %>
          </div>

        <% end %>
      </div>
  </div>
</div>