SkillTest/config/routes.rb
Rails.application.routes.draw do

  #ユーザー登録
  namespace :admin do
    root :to => 'home#index'
    resource :user,:except => [:index]
    resources :home, :only => [:index]
    resources :user_sessions, :only => [:new, :create, :destroy]
    resources :sites, :products
  end
  
  #ログイン
  get    'login',   to: 'admin/user_sessions#new'
  post   'login',   to: 'admin/user_sessions#create'
  get '/admin/logout' => 'admin/user_sessions#destroy', :as => 'admin_logout'
  
  
  concern :taggables do
    resources :tags, only: [:index]
  end
  
  #フロント
  resources :sites, path: '', only: [:index, :show] do
    resources :products, concerns: :taggables, only: [:show]
    resources :tags, only: [:show]
  end
  
  #エラーハンドリング
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

SkillTest/app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
  
  validates :name,:explanation, presence: true
  validates :site_url, uniqueness: true, presence: true ,format: { with: /\A[a-zA-Z0-9]+\Z/, message: "空白／記号なしの文字列を入力してください。" }
  
  #サイト名で検索出来るよう
  include FriendlyId
  friendly_id :site_url
  
  #画像アップロード用
  mount_uploader :image, ImageUploader
  
  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.active = true if self.active.nil?
  end
  
end

SkillTest/app/controllers/admin/sites_controller.rb
class Admin::SitesController < Admin::BaseController
  before_action :require_login
  before_action :get_site, only: [:edit,:update,:destroy]
  before_action only: [:edit,:update,:destroy]do
    check_valid_user(@site)
  end
  
  def index
    @user = current_user
  end  
  
  def show
    @user = current_user
    @site = Site.friendly.find(params[:id])

  end
  
  def new
    @site = Site.new
  end
  
  def edit  
  end
  
  def create
     @user = current_user
     @site = Site.new(site_params)
     @site.user = @user
    
    if @site.save
    redirect_to admin_site_path(@site)
    else
      render 'new'
    end
  end
  
  def update   
    if @site.update(site_params)
      redirect_to admin_site_path(@site)
    else
      render 'edit'
    end  
  end

  def destroy     
      if @site.destroy
        redirect_to admin_sites_path,notice: '削除成功しました。'
      else
        redirect_to admin_sites_path,alert: '削除失敗しました。'
      end
  end
  
  private
    def site_params
      params.require(:site).permit(:name, :explanation, :site_url, :active, :image)
    end
end

SkillTest/app/controllers/sites_controller.rb
class SitesController < FrontBaseController
  
  #サイトトップ
  def index
     render :layout => false
  end

  def show
    @site = Site.friendly.find(params[:id])
    
    @products = Product.where(site_id: @site.id, active: 1)
                .paginate(:page => params[:page])
                .order_id_desc
 
    @tags = Tag.joins(taggings: :product)
                .select(:name)
                .distinct
                .where(:products => {site_id: @site.id})
                .active_taggings

  end
  
end

SkillTest/app/helpers/sites_helper.rb
module SitesHelper
end

SkillTest/app/views/admin/sites/_form.html.erb
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@site.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= a.label :name %><br>
    <%= a.text_field :name %>
  </p>
 
  <p>
  <div>
    <%= a.radio_button :active, true %>  
    <%= a.label :active, "アクティブ", :value => true %>
    
  </div>
  <div>
    <%= a.radio_button :active, false %>  
    <%= a.label :active, "非アクティブ", :value => false %>
    
  </div>  
  <p>
    <%= a.submit %>
  </p>

SkillTest/app/views/admin/sites/edit.html.erb
<div id = "main" class= "col-lg-12">
  <h1>サイト更新</h1>

  <%= form_for @site, url: admin_site_path, method: :put do |a| %>
    <% if @site.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= @site.errors.count %>
          エラーで保存出来ませんでした。ご確認ください。
        </h2>
        <ul>
          <% @site.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <p>
      <strong><%= a.label :name %></strong><br>
      <%= a.text_field :name %>
    </p>

    <p>
      <strong><%= a.label :explanation, "サイト説明" %></strong><br>
      <%= a.text_field :explanation %>
    </p>

    <p>
      <strong><%= a.label :image, "サイトトップ画像" %></strong><br>
      <%= a.file_field :image , {class: "mb20"} %><br>

      (推奨サイズ：2000px X 300px)
    </p>

    <p>
      <div>
        <%= a.radio_button :active, true %>  
        <%= a.label :active, "アクティブ", :value => true %>
      </div>

      <div>
        <%= a.radio_button :active, false %>  
        <%= a.label :active, "非アクティブ", :value => false %>
      </div> 
    </p>
    
    <p>
      <%= a.submit %>
    </p>

  <% end %>

  <%= link_to '戻る', admin_sites_path %>
</div>

SkillTest/app/views/admin/sites/index.html.erb
<div id = "main" class= "col-lg-12">
  <h1>サイト管理</h1>

  <% if flash[:notice] %>
    <p id="notice" class="pop_up">
      <%= flash[:notice] %>
    </p>
  <% end %>
   
  <% if flash[:alert] %>  
    <p id="alert" class="pop_up">
      <%= flash[:alert] %>
    </p>    
  <% end %>
    
  <table>
    <% @user.sites.each do |site| %>
      <tr>
        <td class="admin_site_name"><%= site.name %></td>
        <td><%= link_to '詳細', admin_site_path(site), {class:"btn btn-outline-primary"} %></td>
        <td><%= link_to '変更', edit_admin_site_path(site), {class:"btn btn-outline-success"} %></td>
        <td><%= link_to '削除', admin_site_path(site),
                method: :delete,
                data: { confirm: 'サイトを削除してもよろしいでしょうか？' }, 
                class:"btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to "サイト登録",  new_admin_site_path,{class:"btn btn-primary"} %><br> 

</div> 

SkillTest/app/views/admin/sites/new.html.erb
<h1 class="admin_header">サイト登録</h1>

<%= form_for @site, :url => admin_sites_path, :method => :post do |a| %>
    <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= @site.errors.count %>
        エラーで保存出来ませんでした。ご確認ください。
      </h2>
      <ul>
        <% @site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= a.label :name,"サイト名" %><br>
    <%= a.text_field :name %>
  </p>
  
  <p>
    <%= a.label :site_url,"サイトURL" %><br>
    <%= a.text_field :site_url %>
  </p>
   <p>
    <%= a.label :explanation, "サイト説明" %><br>
    <%= a.text_field :explanation %>
  </p>
  
  <p>
    <%= a.label :image, "サイトトップ画像" %><br>
    <%= a.file_field :image , {class: "mb20"}%><br>
    
    (推奨サイズ：2000px X 300px)
  </p>
  
  <p>
  <div>
    <%= a.radio_button :active, true %>  
    <%= a.label :active, "アクティブ", :value => true %>
    
  </div>
  <div>
    <%= a.radio_button :active, false %>  
    <%= a.label :active, "非アクティブ", :value => false %>
    
  </div>  
  <p>
    <%= a.submit %>
  </p>

<% end %>

SkillTest/app/views/admin/sites/show.html.erb
<div id = "main" class= "col-lg-12">
  <h1>サイト詳細</h1>

  <p>
    <strong>サイト名：</strong>
    <br>
    <%= @site.name %>
  </p>

  <p>
    <strong>サイト説明：</strong>
    <br>
    <%= @site.explanation %>
  </p>
  
  <p>
    <strong>サイトURL：</strong>
    <br>
    <%= link_to @site.site_url, site_path(@site.site_url), target: "_blank" %>
  </p>
  
  
  <p>
    <strong>サイトトップ画像:</strong>
    <br>
    <%= image_tag @site.image, width: "500" %>
  </p>

  <p>
    <strong>アクテイブ：</strong>
    <br>
    <% if @site.active == true %>
      有効
     <% else %>
      無効
    <% end %>
  </p>

  <p>
    <%= link_to "商品一覧へ", admin_products_path(:site_id => @site.id),{class:"btn btn-primary"} %>
  </p>

  <%= link_to '編集', edit_admin_site_path(@site) %> |
  <%= link_to '戻る', admin_sites_path %>

</div>  