SkillTest/config/routes.rb
Rails.application.routes.draw do

  #ユーザー登録
  namespace :admin do
    root :to => 'home#index'
    resource :user,:except => [:index]
    resources :home, :only => [:index]
    resources :user_sessions, :only => [:new, :create, :destroy]
    resources :sites, :products
  end
  
  #ログイン
  get    'login',   to: 'admin/user_sessions#new'
  post   'login',   to: 'admin/user_sessions#create'
  get '/admin/logout' => 'admin/user_sessions#destroy', :as => 'admin_logout'
  
  
  concern :taggables do
    resources :tags, only: [:index]
  end
  
  #フロント
  resources :sites, path: '', only: [:index, :show] do
    resources :products, concerns: :taggables, only: [:show]
    resources :tags, only: [:show]
  end
  
  #エラーハンドリング
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

SkillTest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  #Scope
  scope :order_id_desc, -> { order(id: :desc) }
  scope :active, -> { where active: 1 }
end

SkillTest/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :site
  
  #バリデーション
  validates :amazon_id, :price, :image, :title, :description, presence: true
  
  after_initialize :set_defaults, unless: :persisted?
  
  #画像アップロード用
  mount_uploader :image, ImageUploader
  
  #タグ用
  acts_as_taggable_on :tags
  
  #Pager用 - ページごとの数
  self.per_page = 20

  def set_defaults
    self.active = true if self.active.nil?
  end
end

SkillTest/app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
  
  validates :name,:explanation, presence: true
  validates :site_url, uniqueness: true, presence: true ,format: { with: /\A[a-zA-Z0-9]+\Z/, message: "空白／記号なしの文字列を入力してください。" }
  
  #サイト名で検索出来るよう
  include FriendlyId
  friendly_id :site_url
  
  #画像アップロード用
  mount_uploader :image, ImageUploader
  
  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.active = true if self.active.nil?
  end
  
end

SkillTest/app/models/tag.rb
class Tag < ApplicationRecord
  include FriendlyId
  friendly_id :name  
  has_many  :taggings
  
  #Scope
  scope :active_taggings, -> { where("taggings_count > ? ", 0) }
  
  
  def self.it content
    Tag.where(content).first_or_create! rescue nil
  end
end

SkillTest/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :product,
  foreign_key: "taggable_id"
end

SkillTest/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :sites, dependent: :destroy

  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

SkillTest/app/controllers/front_base_controller.rb
class FrontBaseController < ApplicationController
  layout 'front'
end

SkillTest/app/controllers/products_controller.rb
class ProductsController < FrontBaseController
  before_action :get_site 
  
  def show
    @product = Product
               .includes(:site)
               .where(id: params[:id])
               .active
               .first
               
    
    if @product.blank?
      raise ActionController::RoutingError.new('商品が見つかりません。')
    end
    
    @related_products = Product
                        .tagged_with(@product.tag_list)
                        .where
                        .not(id: @product.id)
                        .limit(5)
  end
end

SkillTest/app/controllers/sites_controller.rb
class SitesController < FrontBaseController
  
  #サイトトップ
  def index
     render :layout => false
  end

  def show
    @site = Site.friendly.find(params[:id])
    
    @products = Product.where(site_id: @site.id, active: 1)
                .paginate(:page => params[:page])
                .order_id_desc
 
    @tags = Tag.joins(taggings: :product)
                .select(:name)
                .distinct
                .where(:products => {site_id: @site.id})
                .active_taggings

  end
  
end

SkillTest/app/controllers/tags_controller.rb
class TagsController < FrontBaseController
  before_action :get_site
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  
  def index
    @product = Product.find(params[:product_id])
  end
  
  def show  
    if Tag.friendly.exists?(params[:id])
      @tag = Tag.friendly.find(params[:id]) 
      @products = Product.joins("inner join taggings tg on products.id = tg.taggable_id inner join tags on tags.id = tg.tag_id")
                          .where(site_id: @site.id).where(tags: {name: @tag.name})
                          .paginate(:page => params[:page])
                          .active
                          .order_id_desc
      if @products.blank?
        flash[:alert] = "対象の商品が存在しません。"
      end
    else
      #フロントに検索したタグを表示する
      @tag = Tag.new
      @tag.name = params[:id]
      flash[:alert] = "タグが存在しません。"
    end
  end
  
  private 
  def record_not_found
    raise ActionController::RoutingError.new('サイト見つかりませんでした。')
  end
end

SkillTest/app/helpers/admin_helper.rb
module AdminHelper
end

SkillTest/app/helpers/admin_home_helper.rb
module AdminHomeHelper
end

SkillTest/app/helpers/application_helper.rb
module ApplicationHelper
end

SkillTest/app/helpers/base_helper.rb
module BaseHelper
end

SkillTest/app/helpers/front_site_helper.rb
module FrontSiteHelper
end

SkillTest/app/helpers/product_helper.rb
module ProductHelper
end

SkillTest/app/helpers/sites_helper.rb
module SitesHelper
end

SkillTest/app/helpers/tags_helper.rb
module TagsHelper
end

SkillTest/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

SkillTest/app/helpers/users_helper.rb
module UsersHelper
end

SkillTest/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理画面</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body class="admin_pages">
      <header>
      <nav class="navbar-fixed-top navbar navbar-dark bg-dark">
          <%= link_to "管理画面",  admin_root_path,{:class => "navbar-brand"} %>
          
          <% if current_user %>
            <div class="" id="">
                <span class="nav-item"><%= link_to "ログアウト", admin_logout_path,{:class => "btn btn-outline-light my-2 my-sm-0"} %></span>
            </div>
          <% end %>
      </nav>
    </header>
    <div class="container">
        <div class="">      
          <%= yield %>      
        </div>
    </div>
  </body>
</html>

SkillTest/app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

SkillTest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

SkillTest/app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>サイトトップ</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans|Oswald" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <style>
      /*     Background        */
      div#top_image {
          background-image: url(<%= @site.image.url %>);
      }
    </style>
  </head>
  <body class="front_pages">
      <header

      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
          <%= link_to @site.name,  site_path(@site.site_url),{:class => "navbar-brand"} %> 
    </nav>
  </header>
      <div id="top_image">
          
      </div >
      <div id="top_explanation">
        <%=  @site.explanation %>
      </div>
      
    <div id="top_container" class="container-fluid">      
          <%= yield %>
        </div>
    </div>
  </body>
</html>