SkillTest/config/routes.rb
Rails.application.routes.draw do

  #ユーザー登録
  namespace :admin do
    root :to => 'home#index'
    resource :user,:except => [:index]
    resources :home, :only => [:index]
    resources :user_sessions, :only => [:new, :create, :destroy]
    resources :sites, :products
  end
  
  #ログイン
  get    'login',   to: 'admin/user_sessions#new'
  post   'login',   to: 'admin/user_sessions#create'
  get '/admin/logout' => 'admin/user_sessions#destroy', :as => 'admin_logout'
  
  
  concern :taggables do
    resources :tags, only: [:index]
  end
  
  #フロント
  resources :sites, path: '', only: [:index, :show] do
    resources :products, concerns: :taggables, only: [:show]
    resources :tags, only: [:show]
  end
  
  #エラーハンドリング
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'

end

SkillTest/app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :products, dependent: :destroy
  
  validates :name,:explanation, presence: true
  validates :site_url, uniqueness: true, presence: true ,format: { with: /\A[a-zA-Z0-9]+\Z/, message: "空白／記号なしの文字列を入力してください。" }
  
  #サイト名で検索出来るよう
  include FriendlyId
  friendly_id :site_url
  
  #画像アップロード用
  mount_uploader :image, ImageUploader
  
  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.active = true if self.active.nil?
  end
  
end

SkillTest/app/controllers/admin/sites_controller.rb
class Admin::SitesController < Admin::BaseController
  before_action :require_login
  before_action :get_site, only: [:edit,:update,:destroy]
  before_action only: [:edit,:update,:destroy]do
    check_valid_user(@site)
  end
  
  def index
    @user = current_user
  end  
  
  def show
    @user = current_user
    @site = Site.friendly.find(params[:id])

  end
  
  def new
    @site = Site.new
  end
  
  def edit  
  end
  
  def create
     @user = current_user
     @site = Site.new(site_params)
     @site.user = @user
    
    if @site.save
    redirect_to admin_site_path(@site)
    else
      render 'new'
    end
  end
  
  def update   
    if @site.update(site_params)
      redirect_to admin_site_path(@site)
    else
      render 'edit'
    end  
  end

  def destroy     
      if @site.destroy
        redirect_to admin_sites_path,notice: '削除成功しました。'
      else
        redirect_to admin_sites_path,alert: '削除失敗しました。'
      end
  end
  
  private
    def site_params
      params.require(:site).permit(:name, :explanation, :site_url, :active, :image)
    end
end

SkillTest/app/controllers/sites_controller.rb
class SitesController < FrontBaseController
  
  #サイトトップ
  def index
     render :layout => false
  end

  def show
    @site = Site.friendly.find(params[:id])
    
    @products = Product.where(site_id: @site.id, active: 1)
                .paginate(:page => params[:page])
                .order_id_desc
 
    @tags = Tag.joins(taggings: :product)
                .select(:name)
                .distinct
                .where(:products => {site_id: @site.id})
                .active_taggings

  end
  
end

SkillTest/app/helpers/sites_helper.rb
module SitesHelper
end

SkillTest/app/views/sites/index.html.erb
Welcome to this website registration service.

SkillTest/app/views/sites/show.html.erb
<div id = "main" class= "col-lg-12">
  <h1 class="text-right site-heading">Products</h1>

    <div class="product_area">
      <% @products.each do |product| %>
        
        <div class="grid-item">    
            <%=link_to(site_product_path(params[:id],product)) do%>   
              <div><%= image_tag product.image %></div>
              <div class="product_area_title"><%= product.title %></div>
            <% end %>
        </div>
        
      <% end %>
        
    </div>

  
  
  <h1 class="text-right site-heading">Tags</h1>
    <div class="tag_area">
      <% @tags.each do |tag| %>

            <%=link_to tag.name, site_tag_path(params[:id],tag.name), { :class=>"grid-item badge badge-pill badge-info" }%>

      <% end %>   
    </div>
  
    <div class="pagination_area">
      <%= will_paginate(@products, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
    </div>
  </div>